# Generated by Django 5.0.6 on 2024-07-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
