# Generated by Django 5.0.6 on 2024-07-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='subskills',
            field=models.ManyToManyField(blank=True, null=True, to='skills.skill'),
        ),
    ]
