# Generated by Django 5.0.6 on 2024-07-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skill_subskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='subskills',
            field=models.ManyToManyField(blank=True, to='skills.skill'),
        ),
    ]
